version: '3.3'

services:
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   env_file: ./.env
   environment:
     - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
     - MYSQL_DATABASE=$MYSQLDB_DATABASE
   ports:
     - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
   volumes:
     - ./mysql-data:/var/lib/mysql
 app:
   depends_on:
     - mysqldb
   build: .
   restart: unless-stopped
   env_file: ./.env
   ports:
     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT 
   volumes:
     - ./:/projeto-empresa-sem-nome
   
   environment:
     - DB_HOST=mysqldb
     - DB_USER=$MYSQLDB_USER
     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
     - DB_NAME=$MYSQLDB_DATABASE
     - DB_PORT=$MYSQLDB_DOCKER_PORT
   stdin_open: true
 app_2:
        container_name: mapa-de-area-react4
        build: ../mapa-de-area-react
        volumes:
            - '../mapa-de-area-react:/app'
            - '/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
